services:
  zookeeper-a2:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-a2
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka1-a2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1-a2
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper-a2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-a2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1-a2:19092,OUTSIDE://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka2-a2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2-a2
    ports:
      - "29093:29093"
    depends_on:
      - zookeeper-a2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-a2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19093,OUTSIDE://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2-a2:19093,OUTSIDE://localhost:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka3-a2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka3-a2
    ports:
      - "29094:29094"
    depends_on:
      - zookeeper-a2
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-a2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19094,OUTSIDE://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3-a2:19094,OUTSIDE://localhost:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

networks:
  default:
    name: kafka-cluster-network
