services:
  zookeeper-a3:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-a3
    ports:
      - "32181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka-a3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-a3
    ports:
      - "39092:9092"
    depends_on:
      - zookeeper-a3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-a3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

networks:
  default:
    name: ave-caesar-net
